Repository jijizhazha1024/go-mall, pull requests merged in 2025-02, with the labels that each got.

#22 fix：认证服务
  .gitignore
  README.md
  common/consts/biz/auth.go
  common/consts/code/auths.go
  common/consts/code/code.go
  common/consts/code/common.go
  common/middleware/auth.go
  common/middleware/clientip.go
  common/response/auths.go
  common/utils/metadatactx/extract.go
  common/utils/token/jwt.go
  common/utils/token/jwt_test.go
  services/auths/auths.proto
  services/auths/auths/auths.pb.go
  services/auths/etc/auths.yaml
  services/auths/internal/config/config.go
  services/auths/internal/logic/authenticationlogic.go
  services/auths/internal/logic/generatetokenlogic.go
  services/auths/internal/logic/renewtokenlogic.go
  services/auths/internal/svc/servicecontext.go
  test/rpc/auths/auths_test.go
Labels: bug

#24 feat：打包脚本
  scripts/build.sh
Labels: feat

#25 构建docker镜像
  Dockerfile
  docker-compose.yml
Labels: bug, feat

#28 线上环境变量配置
  .env.example
  services/auths/auths.go
  services/auths/etc/auths.prod.yaml
  services/auths/internal/logic/authenticationlogic.go
  services/auths/internal/logic/renewtokenlogic.go
Labels: enhancement

#36 feat carts api
  apis/carts/carts.api
  apis/carts/carts.go
  apis/carts/etc/carts-api.prod.yaml
  apis/carts/etc/carts-api.yaml
  apis/carts/internal/config/config.go
  apis/carts/internal/handler/cartitemlisthandler.go
  apis/carts/internal/handler/createcartitemhandler.go
  apis/carts/internal/handler/deletecartitemhandler.go
  apis/carts/internal/handler/routes.go
  apis/carts/internal/handler/updatecartitemhandler.go
  apis/carts/internal/logic/cartitemlistlogic.go
  apis/carts/internal/logic/convert.go
  apis/carts/internal/logic/createcartitemlogic.go
  apis/carts/internal/logic/deletecartitemlogic.go
  apis/carts/internal/logic/updatecartitemlogic.go
  apis/carts/internal/svc/servicecontext.go
  apis/carts/internal/types/types.go
  common/consts/code/carts.go
  common/consts/code/code.go
  dal/model/cart/carts.sql
  dal/model/cart/cartsmodel_gen.go
  go.mod
  go.sum
  services/carts/carts.go
  services/carts/carts.proto
  services/carts/carts/carts.pb.go
  services/carts/carts/carts_grpc.pb.go
  services/carts/cartsclient/carts.go
  services/carts/etc/carts.prod.yaml
  services/carts/internal/logic/cartitemlistlogic.go
  services/carts/internal/logic/createcartitemlogic.go
  services/carts/internal/logic/deletecartitemlogic.go
  services/carts/internal/logic/updatecartitemlogic.go
  services/carts/internal/server/cartserver.go
  services/carts/internal/svc/servicecontext.go
  test/rpc/carts/create/carts_test.go
  test/rpc/carts/delete/carts_test.go
  test/rpc/carts/find/carts_test.go
Labels: feat
